spring.application.name=crypto-market-pulse
spring.profiles.default=processing
server.port=8080
spring.jackson.generator.write-bigdecimal-as-plain=true

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/crypto_market_pulse}
spring.datasource.username=${DB_USERNAME:crypto_user}
spring.datasource.password=${DB_PASSWORD:crypto_password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

coinbase.ws.enabled=${COINBASE_WS_ENABLED:true}
coinbase.ws.url=${COINBASE_WS_URL:wss://ws-feed.exchange.coinbase.com}
coinbase.ws.symbol=BTC-USD
coinbase.ws.reconnect-delay=5s
coinbase.ws.max-reconnect-delay=60s
coinbase.ws.reconnect-jitter-factor=0.20

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
app.kafka.market-trades-topic=${APP_KAFKA_MARKET_TRADES_TOPIC:market-trades}
