spring.application.name=ingestion-service
spring.main.web-application-type=none

coinbase.ws.enabled=${COINBASE_WS_ENABLED:true}
coinbase.ws.url=${COINBASE_WS_URL:wss://ws-feed.exchange.coinbase.com}
coinbase.ws.symbol=BTC-USD
coinbase.ws.reconnect-delay=5s
coinbase.ws.max-reconnect-delay=60s
coinbase.ws.reconnect-jitter-factor=0.20

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false
app.kafka.market-trades-topic=${APP_KAFKA_MARKET_TRADES_TOPIC:market-trades}
